In [2]:
import numpy as np

In [11]:
def ex1(mat, vec):
    # check shape 0 and 1 are equal to x's shape 0
    if mat.shape[0] != vec.shape[0] or mat.shape[1] != vec.shape[0]:
        return
    n = mat.shape[0]
    B = mat.T - np.diag(np.diag(mat))
    print(B)
    X = vec.T
    for i in range(1,n):
        np.concatenate(X,i*vec.T)
    return B + X

In [14]:
A = np.array([[11,-7,4],[4,0,8],[7,8,7]])
x = np.array([[10,11,13]]).T
C = ex1(A,x)
print(C)

[[ 0  4  7]
 [-7  0  8]
 [ 4  8  0]]


TypeError: only integer scalar arrays can be converted to a scalar index

In [18]:
P=np.zeros((3,9))
x=np.block([[A,A]])

In [32]:
np.concatenate([np.array([1,2]),np.array([1,2])])

array([1, 2, 1, 2])